a = input('Digite algo')
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaco?',a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('alfanumerico?', a.isalnum())
print('Está em maiúsculo?', a.isupper())
print('Está em minusculo?', a.islower())
print('Está capitalizada?', a.istitle())

